openapi: 3.0.0
servers:
  - description: The UM kgrid
    url: 'http://kgrid.med.umich.edu/stack2/knowledgeObject'
info:
  description: Icon array resource object - returns js to generate icon arrays
  version: "1.0.0"
  title: Icon Array
paths:
  /99999/fk40s01p75/v0.0.2/iconarray:
    get:
      tags:
        - developers
      summary: returns javascript code for generating an icon array
      responses:
        '200':
          description: the code for generating an icon array
          content:
            text/plain:
              schema:
                type: string