openapi: 3.0.0
servers:
  - description: The UM kgrid
    url: 'http://kgrid.med.umich.edu/v0.0.3'
info:
  description: Icon array resource object - returns js to generate icon arrays
  version: 1.0.0
  title: Icon Array
paths:
  /model/resource/iconarray.js:
    get:
      description: iconarray.
      operationId: iconarray.js
      summary: returns javascript code for generating an icon array
      responses:
        '200':
          description: the code for generating an icon array
          content:
            application/javascript:
              schema:
                type: string
