openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Icon Array'
  description: 'JavaScript object to generate visual representation of risk scores.'
servers:
  - url: '/icon/array/v0.0.1'
paths:
  /model/resource/iconarray.js:
    get:
      description: Get the resource.
      operationId: iconarrayjs
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
